/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    MyColorSelector: typeof import('./src/components/MyColorSelector.vue')['default']
    MyDialog: typeof import('./src/components/MyDialog.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader.vue')['default']
    MyInputBox: typeof import('./src/components/MyInputBox.vue')['default']
    MyListGroup: typeof import('./src/components/MyListGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
